name: test

on:
  push:
    branches:
      - master
  pull_resquest:
    branches: 
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests day1
        run: |
          for d in day*
          do cd d
          cargo test --verbose
          cd ..
          done

