name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests for all days
        run: |
          for d in day*
          do cd $d
          RUST_MIN_STACK=4194304 cargo test --verbose
          cd ..
          done

